---
- hosts: keepalived_hosts
  tasks:
  - name: commands
    shell: haproxyctl show health | grep "{{SERVER}}" | awk '{print $1 "/" $2}'
    register: output
    tags:
      - commands

  - name: enable/disable a service/server
    shell: haproxyctl "{{ACTION}}" server "{{item}}"
    with_items:
      - "{{output.stdout_lines}}"
    tags:
      - action

  - name: list_service
    shell: haproxyctl show health | egrep -v "BACKEND|FRONTEND|pxname" | sort -k2
    register: list_service
    tags:
      - list_service
  - debug: msg="{{list_service.stdout_lines}}"
    tags:
      - list_service